# Generated by Django 5.1.6 on 2025-02-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="telegram_id",
            field=models.CharField(unique=True),
        ),
    ]
