# Generated by Django 5.1.5 on 2025-02-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0002_alter_actor_second_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="actor",
            unique_together={("first_name", "second_name", "last_name")},
        ),
    ]
