# Generated by Django 5.1.2 on 2024-11-08 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actors", "0001_initial"),
        ("directors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=75, unique=True, verbose_name="Title"),
                ),
                ("description", models.TextField(max_length=500)),
                ("release_date", models.DateField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Horror", "horror"),
                            ("Romance", "romance"),
                            ("Comedy", "comedy"),
                            ("Action", "action"),
                            ("Sci-Fi", "sci-fi"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovieActor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(default="Unknown", max_length=15)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies",
                        to="actors.actor",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actors",
                        to="movies.movie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovieDirector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        default="Unknown",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="movies",
                        to="directors.director",
                    ),
                ),
                (
                    "movie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="director",
                        to="movies.movie",
                    ),
                ),
            ],
        ),
    ]
