# Generated by Django 5.1.2 on 2024-11-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="slug",
            field=models.SlugField(default=1, max_length=75, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=75, verbose_name="Title"),
        ),
    ]
