# Generated by Django 5.1.2 on 2024-11-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_slug_alter_movie_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                choices=[
                    ("horror", "Horror"),
                    ("romance", "Romance"),
                    ("comedy", "Comedy"),
                    ("action", "Action"),
                    ("sci-fi", "Sci-Fi"),
                ],
                max_length=15,
            ),
        ),
    ]
