# Generated by Django 5.1.2 on 2025-02-03 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directors", "0001_initial"),
        ("movies", "0004_movie_directors_delete_moviedirector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="directors",
        ),
        migrations.CreateModel(
            name="MovieDirector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        default="Unknown",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="movies",
                        to="directors.director",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="directors",
                        to="movies.movie",
                    ),
                ),
            ],
        ),
    ]
