# Generated by Django 5.1.5 on 2025-02-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actors", "0002_alter_actor_second_name"),
        ("directors", "0002_alter_director_second_name"),
        ("movies", "0005_remove_movie_directors_moviedirector"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="moviedirector",
            unique_together={("movie", "director")},
        ),
        migrations.AddConstraint(
            model_name="movieactor",
            constraint=models.UniqueConstraint(
                fields=("movie", "actor", "role"),
                name="uniquetogether_movie_actor_role",
            ),
        ),
    ]
