# Generated by Django 5.1.5 on 2025-02-04 17:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_alter_moviedirector_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("horror", "Horror"),
                        ("romance", "Romance"),
                        ("comedy", "Comedy"),
                        ("action", "Action"),
                        ("sci-fi", "Sci-Fi"),
                    ],
                    max_length=15,
                ),
                size=None,
            ),
        ),
    ]
