# Generated by Django 5.1.5 on 2025-02-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_movie_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="counrty",
            field=models.CharField(
                default="Unknown", max_length=25, verbose_name="Country"
            ),
        ),
    ]
