# Generated by Django 5.1.5 on 2025-02-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_movie_counrty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="counrty",
            new_name="country",
        ),
    ]
