# Generated by Django 5.1.6 on 2025-02-07 07:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_rename_counrty_movie_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("horror", "Horror"),
                        ("romance", "Romance"),
                        ("comedy", "Comedy"),
                        ("action", "Action"),
                        ("sci-fi", "Sci-Fi"),
                        ("drama", "Drama"),
                        ("adventure", "Adventure"),
                        ("fantasy", "Fantasy"),
                        ("historical", "Historical"),
                        ("noir", "Noir"),
                        ("thriller", "Thriller"),
                    ],
                    max_length=15,
                ),
                size=None,
            ),
        ),
    ]
