# Generated by Django 5.1.6 on 2025-02-06 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_rename_counrty_movie_country"),
        ("profiles", "0001_initial"),
        ("reviews", "0003_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.telegramuser",
                verbose_name="Telegram User",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="movies.movie",
                verbose_name="Movie",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("author", "movie")},
        ),
    ]
