# Generated by Django 5.1.5 on 2025-02-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="director",
            name="second_name",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Middle Name"
            ),
        ),
    ]
